//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UTLAgent.TransApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ApiSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Api : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback depositOperationCompleted;
        
        private System.Threading.SendOrPostCallback withdrawOperationCompleted;
        
        private System.Threading.SendOrPostCallback registerOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListofAccountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomersListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLedgerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerAccountBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListofLogsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecordCreditRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPendingCreditRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApprovedCreditRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegisteredAgentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreditAgentAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback isCreditRequestValidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgentAccountDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgentsWithRunningOutFloatOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsValidAgentAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback SystemOverviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterAgentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Api() {
            this.Url = global::UTLAgent.Properties.Settings.Default.PegBank_TransApi_Api;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event depositCompletedEventHandler depositCompleted;
        
        /// <remarks/>
        public event withdrawCompletedEventHandler withdrawCompleted;
        
        /// <remarks/>
        public event registerCompletedEventHandler registerCompleted;
        
        /// <remarks/>
        public event getListofAccountsCompletedEventHandler getListofAccountsCompleted;
        
        /// <remarks/>
        public event getCustomersListCompletedEventHandler getCustomersListCompleted;
        
        /// <remarks/>
        public event getLedgerCompletedEventHandler getLedgerCompleted;
        
        /// <remarks/>
        public event GetCustomerDataCompletedEventHandler GetCustomerDataCompleted;
        
        /// <remarks/>
        public event getCustomerAccountBalanceCompletedEventHandler getCustomerAccountBalanceCompleted;
        
        /// <remarks/>
        public event ListofLogsCompletedEventHandler ListofLogsCompleted;
        
        /// <remarks/>
        public event RecordCreditRequestCompletedEventHandler RecordCreditRequestCompleted;
        
        /// <remarks/>
        public event GetPendingCreditRequestsCompletedEventHandler GetPendingCreditRequestsCompleted;
        
        /// <remarks/>
        public event GetApprovedCreditRequestsCompletedEventHandler GetApprovedCreditRequestsCompleted;
        
        /// <remarks/>
        public event GetRegisteredAgentsCompletedEventHandler GetRegisteredAgentsCompleted;
        
        /// <remarks/>
        public event CreditAgentAccountCompletedEventHandler CreditAgentAccountCompleted;
        
        /// <remarks/>
        public event isCreditRequestValidCompletedEventHandler isCreditRequestValidCompleted;
        
        /// <remarks/>
        public event GetAgentAccountDetailsCompletedEventHandler GetAgentAccountDetailsCompleted;
        
        /// <remarks/>
        public event GetAgentsWithRunningOutFloatCompletedEventHandler GetAgentsWithRunningOutFloatCompleted;
        
        /// <remarks/>
        public event IsValidAgentAccountCompletedEventHandler IsValidAgentAccountCompleted;
        
        /// <remarks/>
        public event SystemOverviewCompletedEventHandler SystemOverviewCompleted;
        
        /// <remarks/>
        public event SendMailCompletedEventHandler SendMailCompleted;
        
        /// <remarks/>
        public event AuthenticateUserCompletedEventHandler AuthenticateUserCompleted;
        
        /// <remarks/>
        public event GetUserDetailsCompletedEventHandler GetUserDetailsCompleted;
        
        /// <remarks/>
        public event RegisterAgentCompletedEventHandler RegisterAgentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deposit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] deposit(string acc_no, double amt) {
            object[] results = this.Invoke("deposit", new object[] {
                        acc_no,
                        amt});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void depositAsync(string acc_no, double amt) {
            this.depositAsync(acc_no, amt, null);
        }
        
        /// <remarks/>
        public void depositAsync(string acc_no, double amt, object userState) {
            if ((this.depositOperationCompleted == null)) {
                this.depositOperationCompleted = new System.Threading.SendOrPostCallback(this.OndepositOperationCompleted);
            }
            this.InvokeAsync("deposit", new object[] {
                        acc_no,
                        amt}, this.depositOperationCompleted, userState);
        }
        
        private void OndepositOperationCompleted(object arg) {
            if ((this.depositCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.depositCompleted(this, new depositCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/withdraw", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] withdraw(string acc_no, double amt) {
            object[] results = this.Invoke("withdraw", new object[] {
                        acc_no,
                        amt});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void withdrawAsync(string acc_no, double amt) {
            this.withdrawAsync(acc_no, amt, null);
        }
        
        /// <remarks/>
        public void withdrawAsync(string acc_no, double amt, object userState) {
            if ((this.withdrawOperationCompleted == null)) {
                this.withdrawOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwithdrawOperationCompleted);
            }
            this.InvokeAsync("withdraw", new object[] {
                        acc_no,
                        amt}, this.withdrawOperationCompleted, userState);
        }
        
        private void OnwithdrawOperationCompleted(object arg) {
            if ((this.withdrawCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.withdrawCompleted(this, new withdrawCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/register", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] register(object[] agentData) {
            object[] results = this.Invoke("register", new object[] {
                        agentData});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void registerAsync(object[] agentData) {
            this.registerAsync(agentData, null);
        }
        
        /// <remarks/>
        public void registerAsync(object[] agentData, object userState) {
            if ((this.registerOperationCompleted == null)) {
                this.registerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterOperationCompleted);
            }
            this.InvokeAsync("register", new object[] {
                        agentData}, this.registerOperationCompleted, userState);
        }
        
        private void OnregisterOperationCompleted(object arg) {
            if ((this.registerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerCompleted(this, new registerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getListofAccounts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getListofAccounts() {
            object[] results = this.Invoke("getListofAccounts", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getListofAccountsAsync() {
            this.getListofAccountsAsync(null);
        }
        
        /// <remarks/>
        public void getListofAccountsAsync(object userState) {
            if ((this.getListofAccountsOperationCompleted == null)) {
                this.getListofAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListofAccountsOperationCompleted);
            }
            this.InvokeAsync("getListofAccounts", new object[0], this.getListofAccountsOperationCompleted, userState);
        }
        
        private void OngetListofAccountsOperationCompleted(object arg) {
            if ((this.getListofAccountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListofAccountsCompleted(this, new getListofAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCustomersList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getCustomersList() {
            object[] results = this.Invoke("getCustomersList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomersListAsync() {
            this.getCustomersListAsync(null);
        }
        
        /// <remarks/>
        public void getCustomersListAsync(object userState) {
            if ((this.getCustomersListOperationCompleted == null)) {
                this.getCustomersListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomersListOperationCompleted);
            }
            this.InvokeAsync("getCustomersList", new object[0], this.getCustomersListOperationCompleted, userState);
        }
        
        private void OngetCustomersListOperationCompleted(object arg) {
            if ((this.getCustomersListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomersListCompleted(this, new getCustomersListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLedger", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getLedger(string account_no, string which_ledger) {
            object[] results = this.Invoke("getLedger", new object[] {
                        account_no,
                        which_ledger});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getLedgerAsync(string account_no, string which_ledger) {
            this.getLedgerAsync(account_no, which_ledger, null);
        }
        
        /// <remarks/>
        public void getLedgerAsync(string account_no, string which_ledger, object userState) {
            if ((this.getLedgerOperationCompleted == null)) {
                this.getLedgerOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLedgerOperationCompleted);
            }
            this.InvokeAsync("getLedger", new object[] {
                        account_no,
                        which_ledger}, this.getLedgerOperationCompleted, userState);
        }
        
        private void OngetLedgerOperationCompleted(object arg) {
            if ((this.getLedgerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLedgerCompleted(this, new getLedgerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomerData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetCustomerData(string account_no) {
            object[] results = this.Invoke("GetCustomerData", new object[] {
                        account_no});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerDataAsync(string account_no) {
            this.GetCustomerDataAsync(account_no, null);
        }
        
        /// <remarks/>
        public void GetCustomerDataAsync(string account_no, object userState) {
            if ((this.GetCustomerDataOperationCompleted == null)) {
                this.GetCustomerDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerDataOperationCompleted);
            }
            this.InvokeAsync("GetCustomerData", new object[] {
                        account_no}, this.GetCustomerDataOperationCompleted, userState);
        }
        
        private void OnGetCustomerDataOperationCompleted(object arg) {
            if ((this.GetCustomerDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerDataCompleted(this, new GetCustomerDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCustomerAccountBalance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double getCustomerAccountBalance(string account_number) {
            object[] results = this.Invoke("getCustomerAccountBalance", new object[] {
                        account_number});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerAccountBalanceAsync(string account_number) {
            this.getCustomerAccountBalanceAsync(account_number, null);
        }
        
        /// <remarks/>
        public void getCustomerAccountBalanceAsync(string account_number, object userState) {
            if ((this.getCustomerAccountBalanceOperationCompleted == null)) {
                this.getCustomerAccountBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerAccountBalanceOperationCompleted);
            }
            this.InvokeAsync("getCustomerAccountBalance", new object[] {
                        account_number}, this.getCustomerAccountBalanceOperationCompleted, userState);
        }
        
        private void OngetCustomerAccountBalanceOperationCompleted(object arg) {
            if ((this.getCustomerAccountBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerAccountBalanceCompleted(this, new getCustomerAccountBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListofLogs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ListofLogs(string type) {
            object[] results = this.Invoke("ListofLogs", new object[] {
                        type});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ListofLogsAsync(string type) {
            this.ListofLogsAsync(type, null);
        }
        
        /// <remarks/>
        public void ListofLogsAsync(string type, object userState) {
            if ((this.ListofLogsOperationCompleted == null)) {
                this.ListofLogsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListofLogsOperationCompleted);
            }
            this.InvokeAsync("ListofLogs", new object[] {
                        type}, this.ListofLogsOperationCompleted, userState);
        }
        
        private void OnListofLogsOperationCompleted(object arg) {
            if ((this.ListofLogsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListofLogsCompleted(this, new ListofLogsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecordCreditRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecordCreditRequest(string accno, double credit) {
            object[] results = this.Invoke("RecordCreditRequest", new object[] {
                        accno,
                        credit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecordCreditRequestAsync(string accno, double credit) {
            this.RecordCreditRequestAsync(accno, credit, null);
        }
        
        /// <remarks/>
        public void RecordCreditRequestAsync(string accno, double credit, object userState) {
            if ((this.RecordCreditRequestOperationCompleted == null)) {
                this.RecordCreditRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecordCreditRequestOperationCompleted);
            }
            this.InvokeAsync("RecordCreditRequest", new object[] {
                        accno,
                        credit}, this.RecordCreditRequestOperationCompleted, userState);
        }
        
        private void OnRecordCreditRequestOperationCompleted(object arg) {
            if ((this.RecordCreditRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecordCreditRequestCompleted(this, new RecordCreditRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPendingCreditRequests", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPendingCreditRequests() {
            object[] results = this.Invoke("GetPendingCreditRequests", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPendingCreditRequestsAsync() {
            this.GetPendingCreditRequestsAsync(null);
        }
        
        /// <remarks/>
        public void GetPendingCreditRequestsAsync(object userState) {
            if ((this.GetPendingCreditRequestsOperationCompleted == null)) {
                this.GetPendingCreditRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPendingCreditRequestsOperationCompleted);
            }
            this.InvokeAsync("GetPendingCreditRequests", new object[0], this.GetPendingCreditRequestsOperationCompleted, userState);
        }
        
        private void OnGetPendingCreditRequestsOperationCompleted(object arg) {
            if ((this.GetPendingCreditRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPendingCreditRequestsCompleted(this, new GetPendingCreditRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApprovedCreditRequests", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetApprovedCreditRequests() {
            object[] results = this.Invoke("GetApprovedCreditRequests", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetApprovedCreditRequestsAsync() {
            this.GetApprovedCreditRequestsAsync(null);
        }
        
        /// <remarks/>
        public void GetApprovedCreditRequestsAsync(object userState) {
            if ((this.GetApprovedCreditRequestsOperationCompleted == null)) {
                this.GetApprovedCreditRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApprovedCreditRequestsOperationCompleted);
            }
            this.InvokeAsync("GetApprovedCreditRequests", new object[0], this.GetApprovedCreditRequestsOperationCompleted, userState);
        }
        
        private void OnGetApprovedCreditRequestsOperationCompleted(object arg) {
            if ((this.GetApprovedCreditRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApprovedCreditRequestsCompleted(this, new GetApprovedCreditRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRegisteredAgents", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRegisteredAgents() {
            object[] results = this.Invoke("GetRegisteredAgents", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRegisteredAgentsAsync() {
            this.GetRegisteredAgentsAsync(null);
        }
        
        /// <remarks/>
        public void GetRegisteredAgentsAsync(object userState) {
            if ((this.GetRegisteredAgentsOperationCompleted == null)) {
                this.GetRegisteredAgentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegisteredAgentsOperationCompleted);
            }
            this.InvokeAsync("GetRegisteredAgents", new object[0], this.GetRegisteredAgentsOperationCompleted, userState);
        }
        
        private void OnGetRegisteredAgentsOperationCompleted(object arg) {
            if ((this.GetRegisteredAgentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegisteredAgentsCompleted(this, new GetRegisteredAgentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreditAgentAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] CreditAgentAccount(string requestId, string acc_no, double amt, string creditedBy) {
            object[] results = this.Invoke("CreditAgentAccount", new object[] {
                        requestId,
                        acc_no,
                        amt,
                        creditedBy});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void CreditAgentAccountAsync(string requestId, string acc_no, double amt, string creditedBy) {
            this.CreditAgentAccountAsync(requestId, acc_no, amt, creditedBy, null);
        }
        
        /// <remarks/>
        public void CreditAgentAccountAsync(string requestId, string acc_no, double amt, string creditedBy, object userState) {
            if ((this.CreditAgentAccountOperationCompleted == null)) {
                this.CreditAgentAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreditAgentAccountOperationCompleted);
            }
            this.InvokeAsync("CreditAgentAccount", new object[] {
                        requestId,
                        acc_no,
                        amt,
                        creditedBy}, this.CreditAgentAccountOperationCompleted, userState);
        }
        
        private void OnCreditAgentAccountOperationCompleted(object arg) {
            if ((this.CreditAgentAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreditAgentAccountCompleted(this, new CreditAgentAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isCreditRequestValid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] isCreditRequestValid(string requestId, string acc_no, double amt) {
            object[] results = this.Invoke("isCreditRequestValid", new object[] {
                        requestId,
                        acc_no,
                        amt});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void isCreditRequestValidAsync(string requestId, string acc_no, double amt) {
            this.isCreditRequestValidAsync(requestId, acc_no, amt, null);
        }
        
        /// <remarks/>
        public void isCreditRequestValidAsync(string requestId, string acc_no, double amt, object userState) {
            if ((this.isCreditRequestValidOperationCompleted == null)) {
                this.isCreditRequestValidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisCreditRequestValidOperationCompleted);
            }
            this.InvokeAsync("isCreditRequestValid", new object[] {
                        requestId,
                        acc_no,
                        amt}, this.isCreditRequestValidOperationCompleted, userState);
        }
        
        private void OnisCreditRequestValidOperationCompleted(object arg) {
            if ((this.isCreditRequestValidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isCreditRequestValidCompleted(this, new isCreditRequestValidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAgentAccountDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetAgentAccountDetails(string acc_no) {
            object[] results = this.Invoke("GetAgentAccountDetails", new object[] {
                        acc_no});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAgentAccountDetailsAsync(string acc_no) {
            this.GetAgentAccountDetailsAsync(acc_no, null);
        }
        
        /// <remarks/>
        public void GetAgentAccountDetailsAsync(string acc_no, object userState) {
            if ((this.GetAgentAccountDetailsOperationCompleted == null)) {
                this.GetAgentAccountDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgentAccountDetailsOperationCompleted);
            }
            this.InvokeAsync("GetAgentAccountDetails", new object[] {
                        acc_no}, this.GetAgentAccountDetailsOperationCompleted, userState);
        }
        
        private void OnGetAgentAccountDetailsOperationCompleted(object arg) {
            if ((this.GetAgentAccountDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgentAccountDetailsCompleted(this, new GetAgentAccountDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAgentsWithRunningOutFloat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAgentsWithRunningOutFloat(string accountNo, double minimumCredit) {
            object[] results = this.Invoke("GetAgentsWithRunningOutFloat", new object[] {
                        accountNo,
                        minimumCredit});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgentsWithRunningOutFloatAsync(string accountNo, double minimumCredit) {
            this.GetAgentsWithRunningOutFloatAsync(accountNo, minimumCredit, null);
        }
        
        /// <remarks/>
        public void GetAgentsWithRunningOutFloatAsync(string accountNo, double minimumCredit, object userState) {
            if ((this.GetAgentsWithRunningOutFloatOperationCompleted == null)) {
                this.GetAgentsWithRunningOutFloatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgentsWithRunningOutFloatOperationCompleted);
            }
            this.InvokeAsync("GetAgentsWithRunningOutFloat", new object[] {
                        accountNo,
                        minimumCredit}, this.GetAgentsWithRunningOutFloatOperationCompleted, userState);
        }
        
        private void OnGetAgentsWithRunningOutFloatOperationCompleted(object arg) {
            if ((this.GetAgentsWithRunningOutFloatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgentsWithRunningOutFloatCompleted(this, new GetAgentsWithRunningOutFloatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsValidAgentAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsValidAgentAccount(string account_number) {
            object[] results = this.Invoke("IsValidAgentAccount", new object[] {
                        account_number});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsValidAgentAccountAsync(string account_number) {
            this.IsValidAgentAccountAsync(account_number, null);
        }
        
        /// <remarks/>
        public void IsValidAgentAccountAsync(string account_number, object userState) {
            if ((this.IsValidAgentAccountOperationCompleted == null)) {
                this.IsValidAgentAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsValidAgentAccountOperationCompleted);
            }
            this.InvokeAsync("IsValidAgentAccount", new object[] {
                        account_number}, this.IsValidAgentAccountOperationCompleted, userState);
        }
        
        private void OnIsValidAgentAccountOperationCompleted(object arg) {
            if ((this.IsValidAgentAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsValidAgentAccountCompleted(this, new IsValidAgentAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SystemOverview", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] SystemOverview() {
            object[] results = this.Invoke("SystemOverview", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void SystemOverviewAsync() {
            this.SystemOverviewAsync(null);
        }
        
        /// <remarks/>
        public void SystemOverviewAsync(object userState) {
            if ((this.SystemOverviewOperationCompleted == null)) {
                this.SystemOverviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSystemOverviewOperationCompleted);
            }
            this.InvokeAsync("SystemOverview", new object[0], this.SystemOverviewOperationCompleted, userState);
        }
        
        private void OnSystemOverviewOperationCompleted(object arg) {
            if ((this.SystemOverviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SystemOverviewCompleted(this, new SystemOverviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMail(object[] paras) {
            this.Invoke("SendMail", new object[] {
                        paras});
        }
        
        /// <remarks/>
        public void SendMailAsync(object[] paras) {
            this.SendMailAsync(paras, null);
        }
        
        /// <remarks/>
        public void SendMailAsync(object[] paras, object userState) {
            if ((this.SendMailOperationCompleted == null)) {
                this.SendMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMailOperationCompleted);
            }
            this.InvokeAsync("SendMail", new object[] {
                        paras}, this.SendMailOperationCompleted, userState);
        }
        
        private void OnSendMailOperationCompleted(object arg) {
            if ((this.SendMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] AuthenticateUser(string username, string password) {
            object[] results = this.Invoke("AuthenticateUser", new object[] {
                        username,
                        password});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string username, string password) {
            this.AuthenticateUserAsync(username, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string username, string password, object userState) {
            if ((this.AuthenticateUserOperationCompleted == null)) {
                this.AuthenticateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserOperationCompleted);
            }
            this.InvokeAsync("AuthenticateUser", new object[] {
                        username,
                        password}, this.AuthenticateUserOperationCompleted, userState);
        }
        
        private void OnAuthenticateUserOperationCompleted(object arg) {
            if ((this.AuthenticateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetUserDetails(string username) {
            object[] results = this.Invoke("GetUserDetails", new object[] {
                        username});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserDetailsAsync(string username) {
            this.GetUserDetailsAsync(username, null);
        }
        
        /// <remarks/>
        public void GetUserDetailsAsync(string username, object userState) {
            if ((this.GetUserDetailsOperationCompleted == null)) {
                this.GetUserDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserDetailsOperationCompleted);
            }
            this.InvokeAsync("GetUserDetails", new object[] {
                        username}, this.GetUserDetailsOperationCompleted, userState);
        }
        
        private void OnGetUserDetailsOperationCompleted(object arg) {
            if ((this.GetUserDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserDetailsCompleted(this, new GetUserDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterAgent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] RegisterAgent(string firstname, string lastname, string telephoneNo, double accountBalance) {
            object[] results = this.Invoke("RegisterAgent", new object[] {
                        firstname,
                        lastname,
                        telephoneNo,
                        accountBalance});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void RegisterAgentAsync(string firstname, string lastname, string telephoneNo, double accountBalance) {
            this.RegisterAgentAsync(firstname, lastname, telephoneNo, accountBalance, null);
        }
        
        /// <remarks/>
        public void RegisterAgentAsync(string firstname, string lastname, string telephoneNo, double accountBalance, object userState) {
            if ((this.RegisterAgentOperationCompleted == null)) {
                this.RegisterAgentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterAgentOperationCompleted);
            }
            this.InvokeAsync("RegisterAgent", new object[] {
                        firstname,
                        lastname,
                        telephoneNo,
                        accountBalance}, this.RegisterAgentOperationCompleted, userState);
        }
        
        private void OnRegisterAgentOperationCompleted(object arg) {
            if ((this.RegisterAgentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterAgentCompleted(this, new RegisterAgentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void depositCompletedEventHandler(object sender, depositCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class depositCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal depositCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void withdrawCompletedEventHandler(object sender, withdrawCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class withdrawCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal withdrawCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void registerCompletedEventHandler(object sender, registerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getListofAccountsCompletedEventHandler(object sender, getListofAccountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListofAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListofAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getCustomersListCompletedEventHandler(object sender, getCustomersListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomersListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomersListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getLedgerCompletedEventHandler(object sender, getLedgerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLedgerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLedgerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetCustomerDataCompletedEventHandler(object sender, GetCustomerDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getCustomerAccountBalanceCompletedEventHandler(object sender, getCustomerAccountBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerAccountBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerAccountBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListofLogsCompletedEventHandler(object sender, ListofLogsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListofLogsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListofLogsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RecordCreditRequestCompletedEventHandler(object sender, RecordCreditRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecordCreditRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecordCreditRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetPendingCreditRequestsCompletedEventHandler(object sender, GetPendingCreditRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPendingCreditRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPendingCreditRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetApprovedCreditRequestsCompletedEventHandler(object sender, GetApprovedCreditRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApprovedCreditRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApprovedCreditRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetRegisteredAgentsCompletedEventHandler(object sender, GetRegisteredAgentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegisteredAgentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegisteredAgentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreditAgentAccountCompletedEventHandler(object sender, CreditAgentAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreditAgentAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreditAgentAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void isCreditRequestValidCompletedEventHandler(object sender, isCreditRequestValidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isCreditRequestValidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isCreditRequestValidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAgentAccountDetailsCompletedEventHandler(object sender, GetAgentAccountDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgentAccountDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgentAccountDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAgentsWithRunningOutFloatCompletedEventHandler(object sender, GetAgentsWithRunningOutFloatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgentsWithRunningOutFloatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgentsWithRunningOutFloatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void IsValidAgentAccountCompletedEventHandler(object sender, IsValidAgentAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsValidAgentAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsValidAgentAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SystemOverviewCompletedEventHandler(object sender, SystemOverviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SystemOverviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SystemOverviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendMailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AuthenticateUserCompletedEventHandler(object sender, AuthenticateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserDetailsCompletedEventHandler(object sender, GetUserDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RegisterAgentCompletedEventHandler(object sender, RegisterAgentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterAgentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterAgentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591